import { useState, useEffect, useCallback, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useAuth } from '@/contexts/AuthContext';
import { api } from '@/lib/api';
import {
  BookOpen, Plus, Pencil, Trash2, X, Save,
  Eye, EyeOff, Loader2, ArrowLeft, Star, Lock, Unlock
} from 'lucide-react';
import { toast } from 'sonner';
import { v4 as uuidv4 } from 'uuid';
import type { Variable, VariableValue } from '@/types/scheduler';
import { useLanguage } from '@/contexts/LanguageContext';

interface PromptTemplate {
  id: number;
  name: string;
  slug: string;
  description: string | null;
  youtube_url: string | null;
  sora_url: string | null;
  /** Reference URL for Grok-generated examples (separate from sora_url/youtube). */
  grok_url: string | null;
  thumbnail_url: string | null;
  platform: string;
  prompt_template: string;
  /** Optional second prompt used by extend models (kie_grok_extend, etc.). */
  extend_prompt_template?: string | null;
  variables: any[];
  /** Variables specific to the extend prompt; same shape as `variables`. */
  extend_variables?: any[];
  is_featured: boolean;
  is_active: boolean;
  yearly_only: boolean;
  display_order: number;
  times_used: number;
}

const AdminPrompts = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { t } = useLanguage();
  const [prompts, setPrompts] = useState<PromptTemplate[]>([]);
  const [loading, setLoading] = useState(true);
  const [editingPrompt, setEditingPrompt] = useState<Partial<PromptTemplate> | null>(null);
  const [saving, setSaving] = useState(false);
  const [variables, setVariables] = useState<Variable[]>([]);
  const [extendVariables, setExtendVariables] = useState<Variable[]>([]);
  const [newVarValue, setNewVarValue] = useState<Record<string, string>>({});
  const [autoGeneratedVars, setAutoGeneratedVars] = useState<Set<string>>(new Set());
  const [autoGenerating, setAutoGenerating] = useState<Record<string, boolean>>({});

  // Extract variables from prompt template (supports {var} and [VAR] formats)
  const extractedVarNames = useMemo(() => {
    if (!editingPrompt?.prompt_template) return [];
    const bracketMatches = editingPrompt.prompt_template.match(/\{([^}]+)\}/g) || [];
    const squareMatches = editingPrompt.prompt_template.match(/\[([^\]]+)\]/g) || [];
    const allMatches = [...bracketMatches, ...squareMatches];
    const names = allMatches.map(m => m.replace(/[\{\}\[\]]/g, ''));
    return [...new Set(names)]; // unique names
  }, [editingPrompt?.prompt_template]);

  // Extract variables from extend prompt template
  const extractedExtendVarNames = useMemo(() => {
    if (!editingPrompt?.extend_prompt_template) return [];
    const bracketMatches = editingPrompt.extend_prompt_template.match(/\{([^}]+)\}/g) || [];
    const squareMatches = editingPrompt.extend_prompt_template.match(/\[([^\]]+)\]/g) || [];
    const allMatches = [...bracketMatches, ...squareMatches];
    const names = allMatches.map(m => m.replace(/[\{\}\[\]]/g, ''));
    return [...new Set(names)];
  }, [editingPrompt?.extend_prompt_template]);

  // Sync variables when extracted names change
  useEffect(() => {
    if (!editingPrompt) return;

    setVariables(prev => {
      const existing = prev.filter(v => extractedVarNames.includes(v.name));
      const newVars = extractedVarNames
        .filter(name => !prev.some(v => v.name === name))
        .map(name => ({ name, values: [], loop: true }));
      return [...existing, ...newVars];
    });
  }, [extractedVarNames, editingPrompt]);

  // Sync extend variables when extracted names change
  useEffect(() => {
    if (!editingPrompt) return;

    setExtendVariables(prev => {
      const existing = prev.filter(v => extractedExtendVarNames.includes(v.name));
      const newVars = extractedExtendVarNames
        .filter(name => !prev.some(v => v.name === name))
        .map(name => ({ name, values: [], loop: true }));
      return [...existing, ...newVars];
    });
  }, [extractedExtendVarNames, editingPrompt]);

  // Auto-generate disabled for admin — admin ใส่ตัวแปรเอง

  // Load variables when editing existing prompt
  useEffect(() => {
    if (editingPrompt?.variables) {
      // Mark existing variables as already auto-generated so we don't re-generate
      const existingNames = editingPrompt.variables
        .filter(v => v.values && v.values.length > 0)
        .map(v => v.name || '');
      setAutoGeneratedVars(new Set(existingNames));
      setVariables(editingPrompt.variables.map(v => ({
        name: v.name || '',
        values: v.values || [],
        loop: v.loop || false,
        system_prompt: v.system_prompt || `Generate a diverse list of "${v.name}" values. Each value should be unique and creative. Output only the values, one per line.`,
      })));
    }
    if (editingPrompt?.extend_variables) {
      setExtendVariables(editingPrompt.extend_variables.map(v => ({
        name: v.name || '',
        values: v.values || [],
        loop: v.loop || false,
        system_prompt: v.system_prompt || '',
      })));
    }
  }, [editingPrompt?.id]);

  const PROMPT_MANAGER_EMAILS = ['basballcmmilk@gmail.com', 'xommon101@gmail.com'];
  const canAccessPrompts = user?.isAdmin || PROMPT_MANAGER_EMAILS.includes(user?.email || '');

  useEffect(() => {
    if (!canAccessPrompts) {
      navigate('/');
      return;
    }
    loadPrompts();
  }, [user, navigate]);

  const loadPrompts = useCallback(async () => {
    try {
      const data = await api.getAdminPromptTemplates();
      setPrompts(data);
    } catch {
      toast.error(t('admin.loadFailed'));
    } finally {
      setLoading(false);
    }
  }, []);

  const handleAddVariableValue = (varName: string) => {
    const rawValue = newVarValue[varName]?.trim();
    if (!rawValue) return;

    // Support pasting multiple values (split by newline or comma)
    const values = rawValue
      .split(/[\n,]/)
      .map(v => v.trim())
      .filter(v => v.length > 0);

    if (values.length === 0) return;

    setVariables(prev => prev.map(v => {
      if (v.name !== varName) return v;
      const newVals: VariableValue[] = values.map(val => ({
        id: uuidv4(),
        value: val,
        status: 'new'
      }));
      return { ...v, values: [...v.values, ...newVals] };
    }));
    setNewVarValue(prev => ({ ...prev, [varName]: '' }));
    if (values.length > 1) {
      toast.success(t('admin.valuesAdded', { count: values.length.toString() }));
    }
  };

  const handleRemoveVariableValue = (varName: string, valueId: string) => {
    setVariables(prev => prev.map(v => {
      if (v.name !== varName) return v;
      return { ...v, values: v.values.filter(val => val.id !== valueId) };
    }));
  };

  const handleAddExtendVariableValue = (varName: string) => {
    const rawValue = newVarValue[`ext_${varName}`]?.trim();
    if (!rawValue) return;
    const values = rawValue.split(/[\n,]/).map(v => v.trim()).filter(v => v.length > 0);
    if (values.length === 0) return;
    setExtendVariables(prev => prev.map(v => {
      if (v.name !== varName) return v;
      const newVals: VariableValue[] = values.map(val => ({ id: uuidv4(), value: val, status: 'new' }));
      return { ...v, values: [...v.values, ...newVals] };
    }));
    setNewVarValue(prev => ({ ...prev, [`ext_${varName}`]: '' }));
    if (values.length > 1) toast.success(t('admin.valuesAdded', { count: values.length.toString() }));
  };

  const handleRemoveExtendVariableValue = (varName: string, valueId: string) => {
    setExtendVariables(prev => prev.map(v => {
      if (v.name !== varName) return v;
      return { ...v, values: v.values.filter(val => val.id !== valueId) };
    }));
  };


  const handleSave = async () => {
    if (!editingPrompt?.name || !editingPrompt?.prompt_template) {
      toast.error(t('admin.nameAndTemplateRequired'));
      return;
    }
    setSaving(true);
    try {
      const dataToSave = { ...editingPrompt, variables, extend_variables: extendVariables.length > 0 ? extendVariables : undefined };
      if (editingPrompt.id) {
        await api.updateAdminPromptTemplate(editingPrompt.id, dataToSave);
        toast.success(t('admin.promptUpdated'));
      } else {
        await api.createAdminPromptTemplate(dataToSave);
        toast.success(t('admin.promptCreated'));
      }
      setEditingPrompt(null);
      setVariables([]);
      setExtendVariables([]);
      loadPrompts();
    } catch {
      toast.error(t('admin.saveFailed'));
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (!confirm(t('admin.deleteConfirm'))) return;
    try {
      await api.deleteAdminPromptTemplate(id);
      toast.success(t('admin.promptDeleted'));
      loadPrompts();
    } catch {
      toast.error(t('admin.deleteFailed'));
    }
  };

  const handleToggleActive = async (p: PromptTemplate) => {
    try {
      await api.updateAdminPromptTemplate(p.id, { is_active: !p.is_active });
      loadPrompts();
      toast.success(p.is_active ? t('admin.deactivated') : t('admin.activated'));
    } catch {
      toast.error(t('admin.updateFailed'));
    }
  };

  const handleToggleFeatured = async (p: PromptTemplate) => {
    try {
      await api.updateAdminPromptTemplate(p.id, { is_featured: !p.is_featured });
      loadPrompts();
      toast.success(p.is_featured ? t('admin.unfeatured') : t('admin.setFeatured'));
    } catch {
      toast.error(t('admin.updateFailed'));
    }
  };

  const handleToggleYearlyOnly = async (p: PromptTemplate) => {
    try {
      await api.updateAdminPromptTemplate(p.id, { yearly_only: !p.yearly_only });
      loadPrompts();
      toast.success(p.yearly_only ? 'Unlocked for all plans' : 'Locked for yearly only');
    } catch {
      toast.error(t('admin.updateFailed'));
    }
  };

  const newPrompt = () => {
    setVariables([]);
    setNewVarValue({});
    setEditingPrompt({
      name: '', description: '', youtube_url: '', sora_url: '', platform: 'sora2',
      prompt_template: '', variables: [], is_featured: false, is_active: true, display_order: 0
    });
  };

  if (loading) {
    return (
      <div className="page-wrapper flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-[#FFB300]" />
      </div>
    );
  }

  return (
    <div className="page-wrapper">
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto space-y-6">
          {/* Header */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="icon" onClick={() => navigate('/app')}>
                <ArrowLeft className="h-5 w-5" />
              </Button>
              <div>
                <h1 className="text-2xl font-bold flex items-center gap-2">
                  <BookOpen className="h-6 w-6 text-[#FFB300]" />
                  {t('admin.promptManager')}
                </h1>
                <p className="text-muted-foreground text-sm">{prompts.length} {t('admin.templates')}</p>
              </div>
            </div>
            <Button onClick={newPrompt} className="bg-[#FFB300] text-black hover:bg-[#FFB300]/90">
              <Plus className="h-4 w-4 mr-1" />
              {t('admin.addPrompt')}
            </Button>
          </div>

          {/* Edit/Create Form */}
          {editingPrompt && (
            <Card className="border-[#FFB300]/30">
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-lg">{editingPrompt.id ? t('admin.editPrompt') : t('admin.newPrompt')}</CardTitle>
                  <Button variant="ghost" size="icon" onClick={() => { setEditingPrompt(null); setVariables([]); setNewVarValue({}); }}>
                    <X className="h-4 w-4" />
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-medium">{t('admin.nameRequired')}</label>
                    <input
                      className="w-full p-2 rounded bg-input border border-border text-sm mt-1"
                      value={editingPrompt.name || ''}
                      onChange={e => setEditingPrompt({ ...editingPrompt, name: e.target.value })}
                      placeholder={t('admin.promptName')}
                    />
                  </div>
                  <div>
                    <label className="text-sm font-medium">{t('admin.platform')}</label>
                    <select
                      className="w-full p-2 rounded bg-input border border-border text-sm mt-1"
                      value={editingPrompt.platform || 'sora2'}
                      onChange={e => setEditingPrompt({ ...editingPrompt, platform: e.target.value })}
                    >
                      <option value="sora2">Sora2</option>
                      <option value="sora2-vidgo">Sora2 Vidgo</option>
                      <option value="kling">Kling</option>
                      <option value="kie-grok-10s">[KIE] Grok Imagine 10-30s</option>
                      <option value="kie-grok-10s-extend">[KIE] Grok 10s + Extend</option>
                      <option value="other">Other</option>
                    </select>
                  </div>
                </div>

                <div>
                  <label className="text-sm font-medium">{t('admin.description')}</label>
                  <input
                    className="w-full p-2 rounded bg-input border border-border text-sm mt-1"
                    value={editingPrompt.description || ''}
                    onChange={e => setEditingPrompt({ ...editingPrompt, description: e.target.value })}
                    placeholder={t('admin.descPlaceholder')}
                  />
                </div>

                <div>
                  <label className="text-sm font-medium">{t('admin.youtubeUrl')}</label>
                  <input
                    className="w-full p-2 rounded bg-input border border-border text-sm mt-1"
                    value={editingPrompt.youtube_url || ''}
                    onChange={e => setEditingPrompt({ ...editingPrompt, youtube_url: e.target.value })}
                    placeholder="https://youtube.com/shorts/..."
                  />
                </div>

                <div>
                  <label className="text-sm font-medium">Grok URL (วิดีโอตัวอย่าง)</label>
                  <input
                    className="w-full p-2 rounded bg-input border border-border text-sm mt-1"
                    value={editingPrompt.grok_url || ''}
                    onChange={e => setEditingPrompt({ ...editingPrompt, grok_url: e.target.value })}
                    placeholder="https://..."
                  />
                </div>

                {/* Sora URL hidden - ยังไม่พร้อมใช้งาน */}

                <div>
                  <label className="text-sm font-medium">{t('admin.promptTemplateRequired')}</label>
                  <p className="text-xs text-muted-foreground mt-0.5 mb-1">
                    {t('admin.varHint')}
                  </p>
                  <textarea
                    className="w-full p-2 rounded bg-input border border-border text-sm mt-1 min-h-[120px] font-mono"
                    value={editingPrompt.prompt_template || ''}
                    onChange={e => setEditingPrompt({ ...editingPrompt, prompt_template: e.target.value })}
                    placeholder={t('admin.templatePlaceholder')}
                  />
                </div>

                {editingPrompt.platform === 'kie-grok-10s-extend' && (
                  <div className="border border-cyan-500/30 rounded-lg p-4 bg-cyan-950/10 space-y-3">
                    <label className="text-sm font-medium text-cyan-300">Extend Prompt</label>
                    <p className="text-xs text-muted-foreground">
                      Prompt สำหรับต่อวิดีโอเพิ่ม 10 วินาที (รวม ~20s) — ใส่ตัวแปรในรูปแบบ {'{ชื่อตัวแปร}'}
                    </p>
                    <textarea
                      className="w-full p-2 rounded bg-input border border-cyan-500/20 text-sm min-h-[120px] font-mono"
                      value={editingPrompt.extend_prompt_template || ''}
                      onChange={e => setEditingPrompt({ ...editingPrompt, extend_prompt_template: e.target.value })}
                      placeholder="เช่น: Continue the scene smoothly, {character} walks further into {location}..."
                    />

                    {/* Extend Variables Section */}
                    {extractedExtendVarNames.length > 0 && (
                      <div className="border border-cyan-500/20 rounded-lg p-3 bg-cyan-950/20 space-y-3">
                        <label className="text-sm font-medium text-cyan-300">
                          ตัวแปร Extend ({extractedExtendVarNames.length} ตัว)
                        </label>
                        <div className="space-y-4">
                          {extendVariables.map(variable => {
                            const newCount = variable.values.filter(v => v.status === 'new').length;
                            const usedCount = variable.values.filter(v => v.status === 'used').length;
                            return (
                              <div key={variable.name} className="bg-zinc-900/50 rounded-lg p-3 border border-zinc-700">
                                <div className="flex items-center gap-2 mb-2">
                                  <code className="text-sm text-cyan-300 font-mono">{`{${variable.name}}`}</code>
                                  {newCount > 0 && (
                                    <Badge variant="outline" className="text-xs bg-green-500/20 text-green-400 border-green-500/50">
                                      {newCount} {t('admin.new')}
                                    </Badge>
                                  )}
                                  {usedCount > 0 && (
                                    <Badge variant="outline" className="text-xs bg-zinc-500/20 text-zinc-400 border-zinc-500/50">
                                      {usedCount} {t('admin.used')}
                                    </Badge>
                                  )}
                                </div>
                                {variable.values.length > 0 && (
                                  <div className="flex flex-wrap gap-1.5 mb-2">
                                    {variable.values.map(val => (
                                      <span key={val.id} className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs ${val.status === 'new' ? 'bg-green-500/20 text-green-300 border border-green-500/30' : 'bg-zinc-600/30 text-zinc-400 border border-zinc-600/30'}`}>
                                        {val.value}
                                        <button type="button" onClick={() => handleRemoveExtendVariableValue(variable.name, val.id)} className="hover:text-red-400 ml-0.5">
                                          <X className="h-3 w-3" />
                                        </button>
                                      </span>
                                    ))}
                                  </div>
                                )}
                                <div className="flex gap-2">
                                  <textarea
                                    className="flex-1 p-1.5 rounded bg-zinc-800 border border-zinc-600 text-sm min-h-[36px] resize-y"
                                    placeholder={`เพิ่มค่า ${variable.name}`}
                                    value={newVarValue[`ext_${variable.name}`] || ''}
                                    onChange={e => setNewVarValue(prev => ({ ...prev, [`ext_${variable.name}`]: e.target.value }))}
                                    rows={1}
                                  />
                                  <Button type="button" size="sm" onClick={() => handleAddExtendVariableValue(variable.name)} disabled={!newVarValue[`ext_${variable.name}`]?.trim()} className="bg-cyan-600 hover:bg-cyan-700 h-9">
                                    <Plus className="h-4 w-4" />
                                  </Button>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {/* Variables Section */}
                {extractedVarNames.length > 0 && (
                  <div className="border border-emerald-500/30 rounded-lg p-4 bg-emerald-950/20">
                    <label className="text-sm font-medium text-emerald-300 flex items-center gap-2">
                      {t('admin.variables')} ({extractedVarNames.length} {t('admin.varItems')})
                    </label>
                    <p className="text-xs text-muted-foreground mb-3">
                      {t('admin.varDesc')}
                    </p>

                    <div className="space-y-4">
                      {variables.map(variable => {
                        const newCount = variable.values.filter(v => v.status === 'new').length;
                        const usedCount = variable.values.filter(v => v.status === 'used').length;

                        return (
                          <div key={variable.name} className="bg-zinc-900/50 rounded-lg p-3 border border-zinc-700">
                            <div className="flex items-center justify-between mb-2">
                              <div className="flex items-center gap-2">
                                <code className="text-sm text-emerald-300 font-mono">{`{${variable.name}}`}</code>
                                {newCount > 0 && (
                                  <Badge variant="outline" className="text-xs bg-green-500/20 text-green-400 border-green-500/50">
                                    {newCount} {t('admin.new')}
                                  </Badge>
                                )}
                                {usedCount > 0 && (
                                  <Badge variant="outline" className="text-xs bg-zinc-500/20 text-zinc-400 border-zinc-500/50">
                                    {usedCount} {t('admin.used')}
                                  </Badge>
                                )}
                              </div>
                            </div>

                            {/* Values list */}
                            {variable.values.length > 0 && (
                              <div className="flex flex-wrap gap-1.5 mb-2">
                                {variable.values.map(val => (
                                  <span
                                    key={val.id}
                                    className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs ${
                                      val.status === 'new'
                                        ? 'bg-green-500/20 text-green-300 border border-green-500/30'
                                        : 'bg-zinc-600/30 text-zinc-400 border border-zinc-600/30'
                                    }`}
                                  >
                                    {val.value}
                                    <button
                                      type="button"
                                      onClick={() => handleRemoveVariableValue(variable.name, val.id)}
                                      className="hover:text-red-400 ml-0.5"
                                    >
                                      <X className="h-3 w-3" />
                                    </button>
                                  </span>
                                ))}
                              </div>
                            )}

                            {/* Add new value input - supports paste multiple */}
                            <div className="flex gap-2">
                              <textarea
                                className="flex-1 p-1.5 rounded bg-zinc-800 border border-zinc-600 text-sm min-h-[36px] resize-y"
                                placeholder={t('admin.addValuePlaceholder', { name: variable.name })}
                                value={newVarValue[variable.name] || ''}
                                onChange={e => setNewVarValue(prev => ({ ...prev, [variable.name]: e.target.value }))}
                                rows={1}
                              />
                              <Button
                                type="button"
                                size="sm"
                                onClick={() => handleAddVariableValue(variable.name)}
                                disabled={!newVarValue[variable.name]?.trim()}
                                className="bg-emerald-600 hover:bg-emerald-700 h-9"
                              >
                                <Plus className="h-4 w-4" />
                              </Button>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                <div className="flex items-center gap-6">
                  <label className="flex items-center gap-2 text-sm cursor-pointer">
                    <input
                      type="checkbox"
                      checked={editingPrompt.is_featured || false}
                      onChange={e => setEditingPrompt({ ...editingPrompt, is_featured: e.target.checked })}
                    />
                    {t('admin.featured')}
                  </label>
                  <label className="flex items-center gap-2 text-sm cursor-pointer">
                    <input
                      type="checkbox"
                      checked={editingPrompt.is_active !== false}
                      onChange={e => setEditingPrompt({ ...editingPrompt, is_active: e.target.checked })}
                    />
                    {t('admin.active')}
                  </label>
                  <label className="flex items-center gap-2 text-sm cursor-pointer text-purple-400">
                    <input
                      type="checkbox"
                      checked={editingPrompt.yearly_only || false}
                      onChange={e => setEditingPrompt({ ...editingPrompt, yearly_only: e.target.checked })}
                    />
                    🔒 Yearly Only
                  </label>
                  <div className="flex items-center gap-2 text-sm">
                    <label>{t('admin.displayOrder')}</label>
                    <input
                      type="number"
                      className="w-20 p-1.5 rounded bg-input border border-border text-sm"
                      value={editingPrompt.display_order || 0}
                      onChange={e => setEditingPrompt({ ...editingPrompt, display_order: parseInt(e.target.value) || 0 })}
                    />
                  </div>
                </div>

                <div className="flex gap-2 pt-2">
                  <Button onClick={handleSave} disabled={saving} className="bg-green-600 hover:bg-green-700">
                    {saving ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : <Save className="h-4 w-4 mr-1" />}
                    {editingPrompt.id ? t('admin.update') : t('common.create')}
                  </Button>
                  <Button variant="outline" onClick={() => { setEditingPrompt(null); setVariables([]); setNewVarValue({}); }}>{t('common.cancel')}</Button>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Prompt List */}
          {prompts.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center text-muted-foreground">
                {t('admin.noPrompts')}
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-3">
              {prompts.map(p => (
                <Card key={p.id} className={!p.is_active ? 'opacity-50' : ''}>
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between gap-4">
                      <div className="flex items-center gap-4 flex-1 min-w-0">
                        {(() => {
                          const grokMatch = p.grok_url?.match(/grok\.com\/imagine\/post\/([a-f0-9-]+)/);
                          const grokVideoUrl = grokMatch ? `https://imagine-public.x.ai/imagine-public/share-videos/${grokMatch[1]}.mp4` : (p.grok_url?.includes('imagine-public.x.ai') ? p.grok_url : null);
                          if (grokVideoUrl) return (
                            <video src={grokVideoUrl} className="w-20 h-12 rounded object-cover flex-shrink-0" muted loop autoPlay playsInline />
                          );
                          if (p.thumbnail_url) return (
                            <img src={p.thumbnail_url} alt="" className="w-20 h-12 rounded object-cover flex-shrink-0" />
                          );
                          return null;
                        })()}
                        <div className="min-w-0 flex-1">
                          <div className="flex items-center gap-2 flex-wrap">
                            <p className="font-medium">{p.name}</p>
                            <Badge className="bg-[#FFB300]/20 text-[#FFB300] border-[#FFB300]/50 text-xs">{{ sora2: 'Sora2', 'sora2-vidgo': 'Sora2 Vidgo', kling: 'Kling', 'kie-grok-10s': 'Grok 10s', 'kie-grok-10s-extend': 'Grok Extend (20s)' }[p.platform] || p.platform}</Badge>
                            {p.is_featured && <Badge className="bg-yellow-500/20 text-yellow-500 border-yellow-500/50 text-xs">{t('admin.featured')}</Badge>}
                            {p.yearly_only && <Badge className="bg-purple-500/20 text-purple-400 border-purple-500/50 text-xs"><Lock className="w-3 h-3 mr-1" /> Yearly Only</Badge>}
                            {!p.is_active && <Badge className="bg-red-500/20 text-red-400 border-red-500/50 text-xs">{t('admin.inactive')}</Badge>}
                          </div>
                          <p className="text-sm text-muted-foreground mt-1 truncate">
                            {p.description || p.prompt_template.slice(0, 100) + '...'}
                          </p>
                          <p className="text-xs text-muted-foreground mt-1">
                            Used {p.times_used}x | Order: {p.display_order} | Slug: {p.slug}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-1 flex-shrink-0">
                        <Button variant="ghost" size="icon" onClick={() => handleToggleFeatured(p)}
                          title={p.is_featured ? 'Remove featured' : 'Set featured'}>
                          <Star className={`h-4 w-4 ${p.is_featured ? 'text-yellow-500 fill-yellow-500' : 'text-gray-500'}`} />
                        </Button>
                        <Button variant="ghost" size="icon" onClick={() => handleToggleYearlyOnly(p)}
                          title={p.yearly_only ? 'Unlock for all plans' : 'Lock for yearly only'}>
                          {p.yearly_only ? <Lock className="h-4 w-4 text-purple-400" /> : <Unlock className="h-4 w-4 text-gray-500" />}
                        </Button>
                        <Button variant="ghost" size="icon" onClick={() => handleToggleActive(p)}
                          title={p.is_active ? 'Deactivate' : 'Activate'}>
                          {p.is_active ? <Eye className="h-4 w-4 text-green-500" /> : <EyeOff className="h-4 w-4 text-gray-500" />}
                        </Button>
                        <Button variant="ghost" size="icon" onClick={() => {
                          setVariables((p.variables || []).map(v => ({
                            name: v.name || '',
                            values: v.values || [],
                            loop: v.loop || false
                          })));
                          setNewVarValue({});
                          setEditingPrompt({ ...p });
                        }}>
                          <Pencil className="h-4 w-4" />
                        </Button>
                        <Button variant="ghost" size="icon" onClick={() => handleDelete(p.id)}>
                          <Trash2 className="h-4 w-4 text-red-500" />
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default AdminPrompts;
